[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

;JTAG debugging via built-in USB
[env:esp32dev]
lib_deps = adafruit/Adafruit NeoPixel@^1.15.5
upload_protocol = esp-builtin
monitor_speed = 115200
debug_tool = esp-builtin
build_type = debug
debug_speed = 5000                ; JTAG clock speed in kHz
extra_scripts = pre:extra_script.py
targets = compiledb
;debug_init_break = tbreak setup   ; Automatically stop at setup()

;test via COM port
[env:esp32test]
test_framework = unity      ; PlatformIO's default testing framework
