/*
 * ESP32-S3 lesson: 1 x 3 keyboard matrix -> 3-note "synthesizer" on a buzzer.
 *
 *   1 x 3 matrix - every key sits between the row pin and one column pin:
 *
 *     GPIO9 (R1) o--->---[ key C ]---o GPIO10 (C1)   -> note C5
 *     GPIO9 (R1) o--->---[ key D ]---o GPIO11 (C2)   -> note D5
 *     GPIO9 (R1) o--->---[ key E ]---o GPIO12 (C3)   -> note E5
 *
 *   Buzzer (passive) on GPIO5, driven by LEDC (PWM), 50 % duty, pitch = timer
 *   frequency. (An active buzzer would only need duty 0/50 % at one frequency.)
 *
 * Design rules used here:
 *  - no FreeRTOS tasks and no vTaskDelay()/sleep: everything happens inside a
 *    periodic 50 ms esp_timer callback, app_main() returns immediately;
 *  - the callback never blocks and never busy-waits: keys are sampled once per
 *    tick and de-bounced with a tick counter, not with delays;
 *  - pitch is generated by hardware PWM, so the CPU does nothing while a note
 *    is sounding.
 */

#include <inttypes.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "esp_err.h"
#include "esp_log.h"
#include "esp_timer.h"
#include "driver/gpio.h"
#include "driver/ledc.h"

static const char *TAG = "synth";

/* ============================================================
 * 1. Board / wiring configuration
 * ============================================================ */

/* --- fixed time base --- */
#define TICK_MS           50              // one scan + output update per tick

/* --- keyboard matrix: 1 row (R1) x 3 columns (C1..C3) --- */
#define ROW_NUM           1
#define COL_NUM           3
#define KEY_NUM           (ROW_NUM * COL_NUM)

static const gpio_num_t ROW_GPIO[ROW_NUM] = {
    GPIO_NUM_9,                           // R1, driven by us
};

static const gpio_num_t COL_GPIO[COL_NUM] = {
    GPIO_NUM_10,                          // C1
    GPIO_NUM_11,                          // C2
    GPIO_NUM_12,                          // C3
};

/* The row pin is a push-pull output, driven low while scanning; the column pins
 * are inputs with internal pull-ups. A closed key drags its column low:
 * released = 1, pressed = 0. (Keys wired from the column pin straight to GND
 * behave identically.) Flip this to 1 for buttons wired to 3V3 + pull-downs. */
#define KEY_ACTIVE_LEVEL  0

/* A key must keep the same raw value for this many ticks before the state
 * changes: DEBOUNCE_TICKS * TICK_MS = 100 ms of stable reading. */
#define DEBOUNCE_TICKS    2

/* Print a "still alive" status line every N ticks (0 = never). */
#define HEARTBEAT_TICKS   20              // 1 s

/* --- buzzer --- */
#define BUZZER_GPIO       GPIO_NUM_5

/* ============================================================
 * 2. Notes (equal temperament, 5th octave)
 * ============================================================ */

typedef struct {
    const char *name;
    uint32_t    hz;
} note_t;

static const note_t NOTES[] = {
    { "C5", 523 },                        // C5 = 523.25 Hz
    { "D5", 587 },                        // D5 = 587.33 Hz
    { "E5", 659 },                        // E5 = 659.25 Hz
    /* One octave lower, if the buzzer prefers it - then also raise BUZZ_RES to
     * LEDC_TIMER_11_BIT / BUZZ_RES_BITS to 11, see the divider limit below. */
    // { "C4", 262 }, { "D4", 294 }, { "E4", 330 },
};
#define NOTE_NUM      (sizeof(NOTES) / sizeof(NOTES[0]))
#define NOTE_NONE     ((uint8_t)0xFF)

/* [row][column] -> index into NOTES[] */
static const uint8_t KEY_MAP[ROW_NUM][COL_NUM] = {
    { 0, 1, 2 },                          // R1: C1->C5, C2->D5, C3->E5
};

/* ============================================================
 * 3. Buzzer: one LEDC timer + one channel; pitch = timer frequency
 * ============================================================ */

#define BUZZ_MODE         LEDC_LOW_SPEED_MODE
#define BUZZ_TIMER        LEDC_TIMER_0
#define BUZZ_CHANNEL      LEDC_CHANNEL_0
/* The timer divider is at most 255, so the lowest tone a given duty resolution
 * can reach is f_min = 80 MHz / (255 * 2^res): 10 bit -> ~306 Hz, 11 bit ->
 * ~153 Hz, 14 bit -> ~38 Hz. 10 bit is enough for C5..E5. */
#define BUZZ_RES          LEDC_TIMER_10_BIT       // stays fixed for all notes
#define BUZZ_RES_BITS     10
#define BUZZ_DUTY_50      (1u << (BUZZ_RES_BITS - 1))

/* ledc_set_freq() keeps the configured duty resolution, so BUZZ_DUTY_50 keeps
 * meaning "50 %" after every pitch change. (Don't re-run ledc_timer_config()
 * per note: it would let LEDC pick another resolution.) */
static void buzzer_init(void)
{
    gpio_reset_pin(BUZZER_GPIO);          // release the pin from any other role

    const ledc_timer_config_t timer_cfg = {
        .speed_mode      = BUZZ_MODE,
        .timer_num       = BUZZ_TIMER,
        .duty_resolution = BUZZ_RES,
        .freq_hz         = NOTES[0].hz,  // overwritten per note
        .clk_cfg         = LEDC_AUTO_CLK,
    };
    ESP_ERROR_CHECK(ledc_timer_config(&timer_cfg));

    const ledc_channel_config_t chan_cfg = {
        .gpio_num   = BUZZER_GPIO,
        .speed_mode = BUZZ_MODE,
        .channel    = BUZZ_CHANNEL,
        .timer_sel  = BUZZ_TIMER,
        .duty       = 0,                  // silent at boot
        .hpoint     = 0,
    };
    ESP_ERROR_CHECK(ledc_channel_config(&chan_cfg));
}

/* NOTE_NONE -> 0 % duty, i.e. the pin stays low and the buzzer is quiet.
 * A note -> 50 % duty at that note's frequency. */
static void buzzer_apply(uint8_t note)
{
    esp_err_t err = ESP_OK;

    if (note == NOTE_NONE) {
        err = ledc_set_duty(BUZZ_MODE, BUZZ_CHANNEL, 0);
    } else {
        err = ledc_set_freq(BUZZ_MODE, BUZZ_TIMER, NOTES[note].hz);
        if (err == ESP_OK) {
            err = ledc_set_duty(BUZZ_MODE, BUZZ_CHANNEL, BUZZ_DUTY_50);
        }
    }

    if (err == ESP_OK) {
        err = ledc_update_duty(BUZZ_MODE, BUZZ_CHANNEL);
    }

    if (err != ESP_OK) {                     // never abort() from a timer task
        ESP_LOGE(TAG, "buzzer update failed: %s", esp_err_to_name(err));
        return;
    }

    if (note == NOTE_NONE) {
        ESP_LOGI(TAG, "off");
    } else {
        ESP_LOGI(TAG, "on: %s, asked %" PRIu32 " Hz, real %u Hz",
                 NOTES[note].name, NOTES[note].hz,
                 (unsigned)ledc_get_freq(BUZZ_MODE, BUZZ_TIMER));
    }
}

/* ============================================================
 * 4. Keyboard: scan + tick-based de-bounce
 * ============================================================ */

typedef struct {
    bool     raw;        // reading of the current tick (already active-logic)
    bool     raw_prev;   // reading of the previous tick
    uint8_t  stable;     // consecutive ticks with the same raw value
    bool     pressed;    // de-bounced state
    uint32_t stamp;      // press order: bigger = pressed later
} key_t;

static key_t    s_keys[KEY_NUM];
static uint32_t s_press_clock;             // monotonic "who was pressed last"

static void keys_init(void)
{
    /* Row pins: push-pull outputs, idle high so an un-pressed matrix is not
     * pulled to GND (that would short the pull-up of every pressed key). */
    uint64_t row_mask = 0;
    for (size_t r = 0; r < ROW_NUM; r++) {
        row_mask |= BIT(ROW_GPIO[r]);
    }
    const gpio_config_t row_cfg = {
        .pin_bit_mask  = row_mask,
        .mode          = GPIO_MODE_OUTPUT,
        .pull_up_en    = GPIO_PULLUP_DISABLE,
        .pull_down_en  = GPIO_PULLDOWN_DISABLE,
        .intr_type     = GPIO_INTR_DISABLE,
    };
    ESP_ERROR_CHECK(gpio_config(&row_cfg));
    for (size_t r = 0; r < ROW_NUM; r++) {
        ESP_ERROR_CHECK(gpio_set_level(ROW_GPIO[r], 1));
    }

    /* Column pins: input + internal pull-up, read as logic 0 when pressed. */
    uint64_t col_mask = 0;
    for (size_t c = 0; c < COL_NUM; c++) {
        col_mask |= BIT(COL_GPIO[c]);
    }
    const gpio_config_t col_cfg = {
        .pin_bit_mask  = col_mask,
        .mode          = GPIO_MODE_INPUT,
        .pull_up_en    = GPIO_PULLUP_ENABLE,
        .pull_down_en  = GPIO_PULLDOWN_DISABLE,
        .intr_type     = GPIO_INTR_DISABLE,
    };
    ESP_ERROR_CHECK(gpio_config(&col_cfg));
}

/* One scan per tick: pull one row low at a time, sample every column, then put
 * all rows back high. No delays - with pull-ups and mechanical keys 50 ms is
 * far more than the settling time, and the de-bounce counter removes the
 * contact chatter. A 1-row matrix needs exactly one pass. */
static void keys_scan(void)
{
    for (size_t r = 0; r < ROW_NUM; r++) {
        for (size_t i = 0; i < ROW_NUM; i++) {
            gpio_set_level(ROW_GPIO[i], (i == r) ? 0 : 1);
        }
        for (size_t c = 0; c < COL_NUM; c++) {
            s_keys[r * COL_NUM + c].raw =
                (gpio_get_level(COL_GPIO[c]) == KEY_ACTIVE_LEVEL);
        }
    }
    for (size_t i = 0; i < ROW_NUM; i++) {
        gpio_set_level(ROW_GPIO[i], 1);
    }
}

/* Pure state machine: no I/O, no delays. A key changes its debounced state only
 * after DEBOUNCE_TICKS identical raw readings. */
static void keys_debounce(void)
{
    for (size_t i = 0; i < KEY_NUM; i++) {
        key_t *k = &s_keys[i];

        if (k->raw == k->raw_prev) {
            if (k->stable < DEBOUNCE_TICKS) {
                k->stable++;
            }
        } else {
            k->stable = 0;                 // value changed -> restart counting
        }
        k->raw_prev = k->raw;

        if (k->stable >= DEBOUNCE_TICKS && k->pressed != k->raw) {
            k->pressed = k->raw;
            if (k->pressed) {
                k->stamp = ++s_press_clock;
            }
            ESP_LOGI(TAG, "key R%uC%u %s", (unsigned)(i / COL_NUM) + 1,
                     (unsigned)(i % COL_NUM) + 1, k->pressed ? "down" : "up");
        }
    }
}

/* Only one buzzer, so only one note sounds: the most recently pressed key wins
 * (i.e. legato - holding E then pressing D keeps E until E is released). */
static uint8_t keys_current_note(void)
{
    uint8_t     note  = NOTE_NONE;
    uint32_t    best  = 0;

    for (size_t r = 0; r < ROW_NUM; r++) {
        for (size_t c = 0; c < COL_NUM; c++) {
            const key_t *k = &s_keys[r * COL_NUM + c];
            if (k->pressed && k->stamp >= best) {
                best  = k->stamp;
                note  = KEY_MAP[r][c];
            }
        }
    }
    return note;
}

/* ============================================================
 * 5. The 50 ms tick - the whole application lives here
 * ============================================================ */

static void tick_cb(void *arg)
{
    static uint32_t s_tick;
    static uint8_t  s_cur_note = NOTE_NONE;

    s_tick++;

    keys_scan();
    keys_debounce();

    uint8_t note = keys_current_note();
    if (note != s_cur_note) {
        s_cur_note = note;
        buzzer_apply(note);                // logs the new pitch
    }

#if HEARTBEAT_TICKS
    if (s_tick % HEARTBEAT_TICKS == 0) {
        char keys_str[COL_NUM + 1];
        for (size_t c = 0; c < COL_NUM; c++) {
            /* "CDE" when all three are held, ".D." when only the middle one is */
            keys_str[c] = s_keys[c].pressed ? NOTES[KEY_MAP[0][c]].name[0] : '.';
        }
        keys_str[COL_NUM] = '\0';
        ESP_LOGI(TAG, "tick %" PRIu32 ", keys(C D E)=[%s], note=%s", s_tick,
                 keys_str, (note == NOTE_NONE ? "-" : NOTES[note].name));
    }
#endif
}

void app_main(void)
{
    ESP_LOGI(TAG, "ESP32-S3 3-note synth: matrix R1=GPIO%d, C1..C3=GPIO%d/%d/%d, "
             "buzzer=GPIO%d (%d Hz PWM, %d-bit duty)",
             ROW_GPIO[0], COL_GPIO[0], COL_GPIO[1], COL_GPIO[2], BUZZER_GPIO,
             (int)NOTES[0].hz, BUZZ_RES_BITS);
    ESP_LOGI(TAG, "tick=%d ms, debounce=%d ms, no tasks / no delays used",
             TICK_MS, TICK_MS * DEBOUNCE_TICKS);

    keys_init();
    buzzer_init();

    const esp_timer_create_args_t timer_args = {
        .callback = tick_cb,
        .name     = "synth_tick",
    };
    static esp_timer_handle_t s_timer;     // lives for the whole run
    ESP_ERROR_CHECK(esp_timer_create(&timer_args, &s_timer));
    ESP_ERROR_CHECK(esp_timer_start_periodic(s_timer, (uint64_t)TICK_MS * 1000));

    ESP_LOGI(TAG, "running: hold C/D/E to play");
    /* app_main returns: nothing to poll here, the timer task drives everything. */
}
